"""Добавить новую таблицу

Revision ID: f7ef1bcfb105
Revises: 0f900920113f
Create Date: 2025-12-13 16:32:12.565452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ef1bcfb105'
down_revision: Union[str, Sequence[str], None] = '0f900920113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
